# Generated by Django 5.1.4 on 2024-12-26 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round_entry", "0002_hole_shot"),
    ]

    operations = [
        migrations.AddField(
            model_name="hole",
            name="number",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
    ]
