# Generated by Django 5.1.4 on 2025-01-14 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_entry', '0003_hole_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='par',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
    ]
