# Generated by Django 5.1.4 on 2025-10-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_entry', '0004_hole_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='shot_type',
            field=models.CharField(choices=[('drive', 'Drive'), ('approach', 'Approach'), ('around_green', 'Around the Green'), ('putt', 'Putt')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='strokes_gained',
            field=models.FloatField(null=True),
        ),
    ]
