# Generated by Django 5.1.4 on 2025-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_entry', '0005_shot_shot_type_shot_strokes_gained'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
