# Generated by Django 5.1.4 on 2025-10-19 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_entry', '0006_shot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='feet',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddField(
            model_name='shot',
            name='yards',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='shot',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
