# Generated by Django 5.1.4 on 2025-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_entry', '0008_scorecardupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardupload',
            name='parsed_data',
            field=models.JSONField(blank=True, help_text='JSON data parsed from scorecard image for debugging', null=True),
        ),
    ]
